# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# --- Site settings ---
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.variable }}.

title: "Interf3re: A Moiré Pattern Generator"
author: Steph "Six" Schnabel
description: >- # this means to ignore newlines until "baseurl:"
  A Computational and Strategic Analysis for Generative Tooling.
  This site hosts the research paper on the physics, mathematics,
  and computational implementation of Moiré phenomena.

# --- Theme settings ---
# Select a theme for your site. You can find more themes at https://rubygems.org/gems/jekyll-theme-
# The "midnight" theme is a clean, dark-mode theme that fits a technical aesthetic.
# Other good options include: jekyll-theme-minimal, jekyll-theme-cayman, jekyll-theme-primer
theme: jekyll-theme-midnight

# --- Build settings ---
# These settings are for the Jekyll build process.

# A list of plugins to enable. We recommend the jekyll-seo-tag plugin.
plugins:
  - jekyll-seo-tag

# --- Optional settings ---
# These settings are not required but can be useful.

# For the jekyll-seo-tag plugin
# You can uncomment and fill out the following lines to provide more SEO data
# twitter:
#   username: your_twitter_handle
# logo: /assets/logo.png
social:
  name: Steph "Six" Schnabel
  links:
    - https://github.com/6eyFT

# This setting is used by some themes to show a "View on GitHub" link
github:
  repository_url: https://github.com/6eyFT/interf3re